### ISSUE TITLE
Assess deployment options

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/RD-OASIS#5]
Should we deploy this on Heroku (once in a stable state and we have a demo)?

**Comment by AlmightyYakob** [comment]
The API can be deployed on heroku as usual. As for the worker, it would likely need to be deployed in some other fashion, since I don't think we're able to run docker from heroku (we can't install docker without a custom buildpack afaik, and heroku dynos are containers anyway). 

One solution is to just spin up an EC2 instance to run the worker, which is fairly trivial. Setting up the terraform infrastructure for this would be pretty straightforward, but since we need a GPU instance, that could become costly. This worker could also be run on a kitware server.

**Comment by aashish24** [comment]
Related to #29 #28

**Comment by banesullivan** [comment]
Has been discussed and assessed
